name: Linux Container Node Workflow

on: 
# Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: angularwebappcontainer.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        npm run build
        docker build . -t angularwebappcontainer.azurecr.io/webapp:${{ github.sha }}
        docker push angularwebappcontainer.azurecr.io/webapp:${{ github.sha }}
